### ISSUE TITLE
Spawn EACCESS error on node v7.x

### ISSUE THREAD

**Issue by CCristi** [MitocGroup/deep-microservices-todomvc#112]
https://travis-ci.org/MitocGroup/deep-microservices-blue-green/jobs/208112584

**Comment by eistrati** [comment]
Please refer to this link for more details: https://travis-ci.org/MitocGroup/deep-microservices-todomvc/jobs/215273878#L6766

```shell
000
Sleeping 0
00:02:02 GMT+0000 (UTC)  spawn EACCES 
00:02:02 GMT+0000 (UTC)  Error: spawn EACCES
    at exports._errnoException (util.js:1034:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at b.value (/home/travis/.nvm/versions/node/v7.7.4/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:1:1888)
    at b.value (/home/travis/.nvm/versions/node/v7.7.4/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:1:1645)
    at a.module.exports [as _action] (/home/travis/.nvm/versions/node/v7.7.4/lib/node_modules/deepify/bin/commands/server.js:59:19)
    at a.value (/home/travis/.nvm/versions/node/v7.7.4/lib/node_modules/deepify/lib.compiled/Terminal/Program.js:1:4690)
    at a.value (/home/travis/.nvm/versions/node/v7.7.4/lib/node_modules/deepify/lib.compiled/Terminal/Program.js:1:4316)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v7.7.4/lib/node_modules/deepify/bin/deepify.js:105:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3 
```
