### ISSUE TITLE
Command 'which webpack' failed

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/deep-microservices-todomvc#120]
14:19:47 GMT-0400 (EDT)  Command 'which webpack' failed in '/Volumes/Data/Users/eugene/deep-microservices-todomvc' with exit code 1 
14:19:47 GMT-0400 (EDT)  Error: Command 'which webpack' failed in '/Volumes/Data/Users/eugene/deep-microservices-todomvc' with exit code 1
    at Exec._checkError (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:292:21)
    at Exec.runSync (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:142:10)
    at Function.resolve (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/lib.compiled/NodeJS/Bin.js:94:47)
    at Object.<anonymous> (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/bin/commands/compile/helper/webpack.prod.js:37:43)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/bin/commands/compile/helper/compile-lambda.js:12:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Program.module.exports [as _action] (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/bin/commands/compile/prod.js:19:25)
    at Program.run (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/lib.compiled/Terminal/Program.js:254:30)
    at Program.run (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/lib.compiled/Terminal/Program.js:222:32)
    at Program.run (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/lib.compiled/Terminal/Program.js:222:32)
    at Object.<anonymous> (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/bin/deepify.js:117:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3 
14:19:47 GMT-0400 (EDT)  Backend production preparations failed: Error: Command '/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/bin/node /Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/bin/deepify compile prod /Volumes/Data/Users/eugene/deep-microservices-todomvc' failed in '/Volumes/Data/Users/eugene/deep-microservices-todomvc' with exit code 1

**Comment by eistrati** [comment]
I was able to fix it with `npn install -g webpack`, but I think `deepify deploy` should check and install if webpack is missing

**Comment by ddimitrioglo** [comment]
Should we move the issue to https://github.com/MitocGroup/deepify?

**Comment by AlexanderC** [comment]
Webpack should have been installed globally when installing latest deepify: https://github.com/MitocGroup/deepify/blob/master/src/node-bin/assure-deps.sh#L7

**Comment by ddimitrioglo** [comment]
New version released, this issue is not relevant anymore
