### ISSUE TITLE
Command 'npm install deep-framework -g --no-bin-links --only=prod --silent --depth=0' failed

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/deep-microservices-todomvc#121]
14:21:10 GMT-0400 (EDT)  Error: Command '/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/bin/npm install deep-framework -g --no-bin-links --only=prod --silent --depth=0' failed in '/Volumes/Data/Users/eugene/deep-microservices-todomvc' with exit code 1
    at Exec._checkError (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:292:21)
    at ChildProcess.proc.on.code (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:253:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

**Comment by eistrati** [comment]
I was able to fix it by running `npm install -g deep-framework`, but I think `deepify deploy` should check for such failures and fix them by itself

**Comment by ddimitrioglo** [comment]
Should we move the issue to https://github.com/MitocGroup/deepify?

**Comment by AlexanderC** [comment]
@eistrati `deep-framework` seems to fail installing in `exec` inside node because of some circular refs complexity so i think we should add it here:
https://github.com/MitocGroup/deepify/blob/master/src/node-bin/assure-deps.sh#L7

Should we move the issue to deepify?

**Comment by ddimitrioglo** [comment]
New version released, this issue is not relevant anymore
