### ISSUE TITLE
Cannot find module '/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/uglifyjs-webpack-plugin/dist/index.js'

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/deep-microservices-todomvc#122]
Error: Cannot find module '/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/uglifyjs-webpack-plugin/dist/index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/folders/5p/ln6fjm311m78d9swpbkbh8g00000gn/T/tmp-28042c0csk3cYqAQV/.deepify-1497982935422/fe8a6cefc211b4f6793475371e4081a2_1497982975052/webpack.prod.js:3:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by eistrati** [comment]
I was able to fix it by running `npm install -g uglifyjs-webpack-plugin`, but I think `deepify deploy` should fix it by itself

**Comment by ddimitrioglo** [comment]
Should we move the issue to https://github.com/MitocGroup/deepify?

**Comment by AlexanderC** [comment]
uglifyjs-webpack-plugin should have been installed globally when installing latest deepify: https://github.com/MitocGroup/deepify/blob/master/src/node-bin/assure-deps.sh#L7

**Comment by ddimitrioglo** [comment]
New version released, this issue is not relevant anymore

**Comment by ddimitrioglo** [comment]
New version released, this issue is not relevant anymore
