### ISSUE TITLE
ERROR in bootstrap.js from UglifyJs Unexpected token: name

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/deep-microservices-todomvc#123]
ERROR in bootstrap.js from UglifyJs                                                                                             
Unexpected token: name (Marshaler) [bootstrap.js:79,23]
 11% building modules 9/9 modules 0 active14:24:02 GMT-0400 (EDT)  { BundleException: Error: Command '/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/bin/webpack --env.production --progress --color --config=webpack.prod.js --hide-modules' failed in '/var/folders/5p/ln6fjm311m78d9swpbkbh8g00000gn/T/tmp-28761XucrwDG67NyO/.deepify-1497983022436/e47d18580e7a9d9e74c18fcc76550240_1497983041832' with exit code 2
    at webpack.run (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/bin/commands/compile/helper/compile-prod.js:67:23)
    at ChildProcess.proc.on.code (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:259:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12) _code: 400 } 
14:24:02 GMT-0400 (EDT)  Retry compiling /Volumes/Data/Users/eugene/deep-microservices-todomvc/deep-blue-green/backend/src/replication/start lambda without optimizations... 
14:24:02 GMT-0400 (EDT)  Compiling lambda "/Volumes/Data/Users/eugene/deep-microservices-todomvc/deep-blue-green/backend/src/replication/start" (purge=false) 
 11 74% module optimization                                                           
ERROR in bootstrap.js from UglifyJs
Unexpected token: name (S3Synchronizer) [bootstrap.js:83,23]
 90% chunk assets processing14:24:03 GMT-0400 (EDT)  { BundleException: Error: Command '/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/bin/webpack --env.production --progress --color --config=webpack.prod.js --hide-modules' failed in '/var/folders/5p/ln6fjm311m78d9swpbkbh8g00000gn/T/tmp-28761XucrwDG67NyO/.deepify-1497983022436/a044edf1021de2450a7163d3f1c69457_1497983041844' with exit code 2
    at webpack.run (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/bin/commands/compile/helper/compile-prod.js:67:23)
    at ChildProcess.proc.on.code (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:259:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) _code: 400 } 
14:24:03 GMT-0400 (EDT)  Retry compiling /Volumes/Data/Users/eugene/deep-microservices-todomvc/deep-blue-green/backend/src/replication/s3-notification lambda without optimizations... 
14:24:03 GMT-0400 (EDT)  Compiling lambda "/Volumes/Data/Users/eugene/deep-microservices-todomvc/deep-blue-green/backend/src/replication/s3-notification" (purge=false) 
 91%                                       
ERROR in bootstrap.js from UglifyJs
Unexpected token: name (SimpleFilter) [bootstrap.js:78,23]
14:24:03 GMT-0400 (EDT)  { BundleException: Error: Command '/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/bin/webpack --env.production --progress --color --config=webpack.prod.js --hide-modules' failed in '/var/folders/5p/ln6fjm311m78d9swpbkbh8g00000gn/T/tmp-28761XucrwDG67NyO/.deepify-1497983022436/eae46a682a8697c42faadb0226a676b4_1497983041832' with exit code 2
    at webpack.run (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/bin/commands/compile/helper/compile-prod.js:67:23)
    at ChildProcess.proc.on.code (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:259:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) _code: 400 } 
14:24:03 GMT-0400 (EDT)  Retry compiling /Volumes/Data/Users/eugene/deep-microservices-todomvc/deep-blue-green/backend/src/replication/s3-backfill lambda without optimizations... 
14:24:03 GMT-0400 (EDT)  Compiling lambda "/Volumes/Data/Users/eugene/deep-microservices-todomvc/deep-blue-green/backend/src/replication/s3-backfill" (purge=false) 
                             
ERROR in bootstrap.js from UglifyJs
Unexpected token: name (RecordType) [bootstrap.js:78,23]
14:24:03 GMT-0400 (EDT)  { BundleException: Error: Command '/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/bin/webpack --env.production --progress --color --config=webpack.prod.js --hide-modules' failed in '/var/folders/5p/ln6fjm311m78d9swpbkbh8g00000gn/T/tmp-28761XucrwDG67NyO/.deepify-1497983022436/fe8a6cefc211b4f6793475371e4081a2_1497983041831' with exit code 2
    at webpack.run (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/bin/commands/compile/helper/compile-prod.js:67:23)
    at ChildProcess.proc.on.code (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.11.0/lib/node_modules/deepify/node_modules/deep-package-manager/lib.compiled/Helpers/Exec.js:259:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12) _code: 400 }

**Comment by AlexanderC** [comment]
We're using an experimental branch of UglifyJS that is supposed to be used with ES6 https://github.com/mishoo/UglifyJS2/tree/harmony#uglify-es

The work on it is still in progress so it could fail in some lambdas, **BUT** we retry building it without optimizations **automatically**. There is a flag to skip optimizations `deepify compile prod -s`.

There is no stable branch of UglifyJS that works with ES6. For more details read https://github.com/webpack/webpack/issues/2545

**Comment by ddimitrioglo** [comment]
New version released, this issue is not relevant anymore
